### ISSUE TITLE
change the repository name

### ISSUE THREAD

**Issue by jaredsagendorf** [xinbeibei/CSCI-544-Project#1]
Hey Beibei, thanks for setting this up. Could you choose a different name though?

I'm worried the professor or TAs are going to assume this is just a copy of previous work, or will raise issues with this being a former kaggle competition. Additionally, people who are searching google for code used in that kaggle are probably going to find this and may ask questions, which we don't want showing up when the professor or TAs are grading this...

Can you just call it something generic like "CSCI 544 Project" or similar?

**Comment by xinbeibei** [comment]
Already changed. Thanks for reminding me, your concerns make sense.
